-- TASK 4: FULL DESCRIPTION OF BOOKS TABLE
-- All SQL keywords are in UPPERCASE

USE alx_book_store;

SELECT COLUMN_NAME, COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store'
  AND TABLE_NAME = 'Books';
